### ISSUE TITLE
error on editing upload image.

### ISSUE THREAD

**Issue by dadaoerv** [camenduru/DragGAN-colab#2]
deploying on colab and everything works fine.
if I click x and upload my own picture, error occure when I try to set points.
![image](https://github.com/camenduru/DragGAN-colab/assets/46274596/ac17415c-7780-4bac-aaeb-696400247522)

**Comment by anvesh54321** [comment]
same problem

**Comment by ghost** [comment]
same

**Comment by camenduru** [comment]
please try new colab
